version: '3.8'

services:
  web:
    build: .
    image: running_leaderboard:latest
    container_name: running_leaderboard_prod
    ports:
      - "3000:80"
    environment:
      - RAILS_ENV=production
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - DATABASE_URL=sqlite3:///rails/storage/production.sqlite3
    volumes:
      - ./storage:/rails/storage
      - ./log:/rails/log
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/up"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  webhook:
    image: almir/webhook
    container_name: webhook_server
    ports:
      - "9000:9000"
    volumes:
      - ./deploy:/etc/webhook
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./deploy/deploy.sh:/deploy.sh:ro
    command: -verbose -hooks=/etc/webhook/hooks.json -hotreload
    restart: unless-stopped
